ci:
  autofix_prs: false
  autoupdate_schedule: 'monthly'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--enforce-all", "--maxkb=300"]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: ".*(.github.*)$"
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ".*(data.*|extern.*|licenses.*|_static.*|_parsetab.py)$"
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix, --show-fixes ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
