image_pixel_side_value: !!python/tuple
  - 500
  - 1000
  - 10000
  - 100000
n_images_value: !!python/tuple
  - 1
  - 3
  - 5
  - 10
  - 25
sidecar_value: !!python/tuple
  - true
  - false
viewport_pixel_size_value: !!python/tuple
  - 600
  - 1000
  - 2000
  - 4000
with_dq_value: !!python/tuple
  - false
  - true
ui_network_throttling_value: !!python/tuple
  - 0.5
  - 1
  - 5
  - 10
  - 50
  - 100
